### PR TITLE
runCompletion.ts: Respect isFillMode setting

### LINKED ISSUE #51: Disabling fill mode does not disable fill mode
I'm on v0.0.30 of the HuggingFace VSCode plugin.
I'm trying to use the plugin with some models that do not support FIM.
However, after I disabled FIM in the settings, the plugin continues to send requests in FIM format to the server.

### PR DESCRIPTION
**Pull request by matthiasgeihs**
Fixes #51

### CODE REVIEW

**Comment by McPatate** [comment]
Hello @matthiasgeihs, we're currently in the works of massively refactoring the extension.

I think this should be fixed, but please let us know if you still experience this issue after `0.0.39` is released.

**Comment by McPatate** [comment]
`0.1.0` is released, please let me know if everything works as expected now. I'll close the issue if I don't see a reply in the coming days assuming the problem is gone.
Feel free to open another PR in case I close too soon.

**Comment by matthiasgeihs** [comment]
@McPatate Great to see that a new release is out.

Feel free to close this one. I'll reopen if problems persist.

**Comment by McPatate** [comment]
Closing, thanks for taking a shot at this anyways!

**Pull request closed without merging**
